// src/components/akteneinsicht/datei-info/datei-info.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Datei } from '@jp-suite/core';

@Component({
  selector: 'jp-datei-info',
  templateUrl: './datei-info.component.html',
  styleUrls: ['./datei-info.component.css']
})
export class DateiInfoComponent implements OnInit {
  @Output() download = new EventEmitter()
  @Output() showPdfSource = new EventEmitter<Datei>()
  @Input() datei: Datei;
  @Input() downloadRestricted: boolean;

  constructor() { }

  ngOnInit() {
  }

  showPreview(){
    this.showPdfSource.emit(this.datei)
  }
  doDownload() {
    if(!this.downloadRestricted)
      this.download.emit();
  }
}

<div class="jp-dateiinfo">
  <button *ngIf="datei.mimeType == 'application/pdf'" (click)="showPreview()" class="mdl-button jp-dateiinfo__button">
    <i class="material-icons">visibility_alt</i>
  </button>
  <button *ngIf="!downloadRestricted" (click)="doDownload()" class="mdl-button jp-dateiinfo__button">
    <i class="material-icons">save_alt</i>
  </button>
  <span class="jp-dateiinfo__typesize">({{ datei.mimeType | mimetype }}, {{ datei.size | filesize }})</span>
</div>

// src/components/akteneinsicht/DateiInfo.vue
<template>
<div class="jp-dateiinfo">
  <button v-if="datei.mimeType == 'application/pdf'" @click="showPreview()" class="mdl-button jp-dateiinfo__button">
    <i class="material-icons">visibility_alt</i>
  </button>
  <button v-if="!downloadRestricted" @click="doDownload()" class="mdl-button jp-dateiinfo__button">
    <i class="material-icons">save_alt</i>
  </button>
  <span class="jp-dateiinfo__typesize">({{ dateiMimeType }}, {{ dateiSize }})</span>
</div>
</template>

<script lang="ts">
import { defineComponent } from "vue"
import { Datei } from '../../ressources/model'
import {filesizeFilter, mimetypeFilter} from '../../filters'

export default defineComponent({
  name: 'DateiInfo',
  props: {
      datei: Datei,
      downloadRestricted: Boolean
  },
  emits: ['download', 'showPdfSource'],
  computed: {
      dateiMimeType (): string {
        return mimetypeFilter(this.datei.mimeType)
      },
      dateiSize (): string {
        return filesizeFilter(this.datei.size)
      }
  },
  methods: {
      showPreview(){
          this.$emit('show-pdf-source', this.datei)
      },
      doDownload(){
          if (!this.downloadRestricted) this.$emit('download')
      }
  }
})
</script>
