// src/components/auth/AuthInfo.vue
<template>
<div class="mdl-navigation jp-navigation jp-usercontrol">
  <div class="jp-login-info__info-text" v-if="'auth.authInfo$ | async as authInfo'"><!--todo-->
    <div>
    <span>Angemeldet als:&nbsp;</span>
    <strong>{{ authInfo.username }}</strong><br />
    <span>Abmeldung in: <jp-countdown :expiresAt="authInfo.expiresAt"></jp-countdown></span>       
<br/>
    <div class="jp-login-info__buttons">
        <button class="mdl-button mdl-js-button mdl-button--raised jp-login-info__refresh-button jp-changeable-button" @click="refresh()">
            <i class="material-icons jp-changeable-button--hide">refresh</i>
            <span class="jp-changeable-button--show">
              Anmeldung erneuern
            </span>
          </button>

      <button class="mdl-button mdl-js-button mdl-button--raised jp-login-info__logout-button" @click="logout()">
        Abmelden
      </button>
    </div>
  </div>
  </div>
  <div class="jp-login-info__info-text" v-if="!(auth.authInfo$ | async)">
    <div>Sie sind nicht angemeldet.</div>
    <div>
      <a routerLink="login">zur Anmeldung</a>
    </div>
  </div>
</div>

</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: 'AuthInfo',
  data () {
    return {
      updateTimer: null,
      updateTimerSub: ''
    }
  },
  mounted () {
    this.auth.getAuthInfo()
  },
  unmounted () {
    this.updateTimerSub.unsubscribe()
    this.updateTimer = null
  },
  methods: {
    logout() {
      this.authService.logout()
    },
    async refresh() {
      await this.authService.refresh()
    }
  }
})
</script>

<style>
.jp-usercontrol{
  padding-right: 20px;
  padding-left: 20px;
}
.jp-login-info__buttons button{
  width: 100%;
  margin: 8px 0;
}
.jp-login-info__buttons button::first-of-type{
  margin-top: 16px
}
</style>

// src/components/auth/auth-info/auth-info.component.ts
import { Component, OnInit, OnDestroy, AfterViewInit } from '@angular/core';
import { AuthService, AuthStore } from '@jp-suite/core';

import { timer, Subscription, Observable, BehaviorSubject } from 'rxjs';
import { Duration, duration, now } from 'moment';
import { AuthInfo } from 'libs/core/src/lib/model/auth-info';

declare var componentHandler: any;

@Component({
  selector: 'jp-auth-info',
  templateUrl: './auth-info.component.html',
  styleUrls: ['./auth-info.component.css']
})
export class AuthInfoComponent implements OnInit, OnDestroy, AfterViewInit {
  updateTimer: any;
  updateTimerSub: Subscription;

  constructor(private authService: AuthService, public auth: AuthStore) { 
    const authInfo = this.auth.getAuthInfo();
  }

  ngOnInit() {
  }

  ngOnDestroy() {
    this.updateTimerSub.unsubscribe();
    this.updateTimer = null;
  }

  ngAfterViewInit(): void {
    componentHandler.upgradeAllRegistered();
  }

  logout() {
    this.authService.logout();
  }

  refresh() {
    this.authService.refresh().subscribe(
      () => { }
    );
  }
}

<div class="mdl-navigation jp-navigation jp-usercontrol">
  <div class="jp-login-info__info-text" *ngIf="auth.authInfo$ | async as authInfo">
    <div>
    <span>Angemeldet als:&nbsp;</span>
    <strong>{{ authInfo.username }}</strong><br />
    <span>Abmeldung in: <jp-countdown [expiresAt]="authInfo.expiresAt"></jp-countdown></span>       
<br/>
    <div class="jp-login-info__buttons">
        <button class="mdl-button mdl-js-button mdl-button--raised jp-login-info__refresh-button jp-changeable-button" (click)="refresh()">
            <i class="material-icons jp-changeable-button--hide">refresh</i>
            <span class="jp-changeable-button--show">
              Anmeldung erneuern
            </span>
          </button>

      <button class="mdl-button mdl-js-button mdl-button--raised jp-login-info__logout-button" (click)="logout()">
        Abmelden
      </button>
    </div>
  </div>
  </div>
  <div class="jp-login-info__info-text" *ngIf="!(auth.authInfo$ | async)">
    <div>Sie sind nicht angemeldet.</div>
    <div>
      <a routerLink="login">zur Anmeldung</a>
    </div>
  </div>
</div>
