// src/components/main/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { PortalStateService } from '@jp-suite/core';
import { AuthStore, ConfigService, AppOperator } from '@jp-suite/core';

@Component({
  selector: 'jp-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  private config: AppOperator;

  constructor(private stateService: PortalStateService, public auth: AuthStore, private configService: ConfigService) { 
    this.config = configService.getOperatorConfig();
    this.stateService.changeState({
      title: 'Home'
    });
  }

  ngOnInit() {
  }

  get homeWelcomeText(): string {
    return this.config === null || this.config === undefined ? "" : this.config.homeWelcomeText
  }
  get IsLoggedIn(): boolean{
    return !!(this.auth && this.auth.getAuthInfo() && this.auth.getAuthInfo().username)
  }
}

<h2>
  Herzlich willkommen
  {{homeWelcomeText}}
</h2>
<p>
  Hier können Sie Akteneinsicht nehmen. Die Akteneinsicht muss vorher bei Gericht beantragt werden. Wird die Einsicht
  gewährt, erhalten Sie ein Kennwort, das Ihnen den Zugang zur gewünschten Akte eröffnet.
</p>

<p *ngIf="IsLoggedIn">
  <a routerLink="/akteneinsichten" routerLinkActive="jp-navigation__link--activated">Zur elektronischen Akteneinsicht</a>
</p>

// src/components/main/Home.vue
<template>
  <h2>
  Herzlich willkommen
  {{homeWelcomeText}}
</h2>
<p>
  Hier können Sie Akteneinsicht nehmen. Die Akteneinsicht muss vorher bei Gericht beantragt werden. Wird die Einsicht
  gewährt, erhalten Sie ein Kennwort, das Ihnen den Zugang zur gewünschten Akte eröffnet.
</p>

<p v-if="IsLoggedIn">
  <a routerLink="/akteneinsichten" routerLinkActive="jp-navigation__link--activated">Zur elektronischen Akteneinsicht</a>
</p>

</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: 'home',
    computed : {
      homeWelcomeText(): string {
        return this.config === null || this.config === undefined ? "" : this.config.homeWelcomeText
      },
      IsLoggedIn(): boolean{
        return !!(this.auth && this.auth.getAuthInfo() && this.auth.getAuthInfo().username)
      }
    }
})
</script>
