// src/components/auth/login/login.component.ts
import { Component, OnInit, AfterViewInit } from '@angular/core';
import { AuthService, PortalStateService, PortalState, AuthResponse } from '@jp-suite/core';
import { Router } from '@angular/router';
import { AuthErrorCodes } from 'libs/core/src/lib/model/auth-error-codes';
import moment = require('moment');
declare var componentHandler: any;

@Component({
  selector: 'jp-suite-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit, AfterViewInit {
  username: string = '';
  password: string = '';
  hidePW: boolean = true;
  
  isLoading: boolean;
  errorMessage: string;

  constructor(private authService: AuthService, private stateService: PortalStateService, private router: Router) {
    this.isLoading = false;
    this.errorMessage = '';

    this.stateService.changeState({
      title: 'Login'
    });
  }

  ngOnInit() {
    this.hidePW = true;
  }

  ngAfterViewInit(): void {
    componentHandler.upgradeAllRegistered();
  }

  public onLogin() {
    this.isLoading = true;

    this.authService.login(this.username, this.password).subscribe(
      res => {
        if(res.returnCode == AuthErrorCodes.Ok) {
          this.router.navigateByUrl('/akteneinsichten')
        } else {
          this.errorMessage = this.getMessageFromAuthResponse(res);
        }

        this.isLoading = false;
      },
      err => {
        this.errorMessage = "Fehler bei der Anmeldung.";
        this.isLoading = false;
      },
      () => {
      }
    );
  }

  private getMessageFromAuthResponse(response: AuthResponse) : string {
    if(response.returnCode == AuthErrorCodes.Ok)
      return "Anmeldung erfolgreich";
    else if (response.returnCode == AuthErrorCodes.ErrorUserLocked) {
      return "Der Benutzer ist bis " + moment().add(response.errorInfo.unlockedIn, "seconds").format("LT") + " Uhr gesperrt.";
    }
    else if (response.returnCode == AuthErrorCodes.ErrorWrongCredentials)
      return "Die Anmeldedaten sind leider nicht korrekt.";
    else
      return "Fehler bei der Anmeldung.";
  }
}

<form #loginForm="ngForm" class="jp-login-form" (ngSubmit)="onLogin()">

  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label jp-textfield jp-login-form__textfield">
    <input class="mdl-textfield__input" type="text" name="reference" id="reference" [(ngModel)]="username" required>
    <label class="mdl-textfield__label" for="reference">Aktenzeichen</label>
    <span class="mdl-textfield__error">Eingabe erforderlich</span>
  </div>

  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label jp-textfield jp-login-form__textfield">
    <input class="mdl-textfield__input" [type]="hidePW ? 'password' : 'text'" name="password" id="password" [(ngModel)]="password" required>
    <label class="mdl-textfield__label" for="password">Passwort</label>
    <span class="mdl-textfield__error">Eingabe erforderlich</span>
    <i class="material-icons mdl-textfield__label__icon" 
      (mouseleave)="hidePW = true"
      (mouseup)="hidePW = true"
      (mousedown)="hidePW = false"
    >{{hidePW ? 'visibility_off' : 'visibility'}}</i>
  </div>

  <div class="jp-login-form__textfield jp-login-button">
    <button class="mdl-button mdl-js-button mdl-button--raised jp-login-form__button" type="submit">
      <div class="jp-login-form__button-text" *ngIf="!isLoading">Anmelden</div>
      <div class="mdl-spinner mdl-spinner--single-color mdl-js-spinner jp-login-form__button-spinner" [ngClass]="{'is-active' : isLoading}"></div>
    </button>

    <span class="msg-error" *ngIf="errorMessage != ''">
      {{ errorMessage }}
    </span>
  </div>
</form>

// jupo-webui/src/components/auth/Login.vue
<script lang="ts">
import { defineComponent, inject, Ref, ref } from 'vue'
import { AuthStore, AuthStoreKey } from './../../store/authStore'
import { AuthService, AuthServiceKey } from './../../libs/services/AuthService'
import moment from 'moment'

export default defineComponent({
  data() {
    return {
      password: '',
      isLoading: false,
      errorMessage: ''
    }
  },
  mounted(){
    if(this.isloggedIn) this.redirect()
  },
  methods: {
    redirect(){
      this.$router.push('/akteneinsichten')
    },
    async onLogin(){
      this.isLoading = true
      try{
          let resultCode = await this.authService.Login(this.username, this.password)
          
          if (resultCode === WebApi.ReturnCodes.Ok)
            this.redirect()
          else if (resultCode === WebApi.ReturnCodes.ErrorUserLocked)
            this.errorMessage = `Der Benutzer ist bis ${moment().add(this.authService.LastErrorInfo(), "seconds").format("LT")} Uhr gesperrt.`
          else if (resultCode === WebApi.ReturnCodes.ErrorWrongCredentials)
            this.errorMessage = 'Die Anmeldedaten sind leider nicht korrekt.'
          else
            this.errorMessage = 'Fehler bei der Anmeldung.'
        }catch(e){
              console.error(e)
              this.errorMessage = 'Fehler bei der Anmeldung.'
        } finally{
          this.isLoading = false
        }
      }
  }
})
</script> 

<script lang="ts" setup>
  const username: Ref<string> = ref('')
  const hidePW: Ref<boolean> = ref(true)
  const authService: AuthService = inject(AuthServiceKey) as AuthService
  const authStore: AuthStore = inject<AuthStore>(AuthStoreKey)
  const {isLoggedIn} = authStore.useStore()
</script>


<template> 
<form class="jp-login-form" @submit.prevent="onLogin()">
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label jp-textfield jp-login-form__textfield">
    <input id="login_name_input" class="mdl-textfield__input" type="text" autocomplete="username" 
      name="reference" v-model="username" required>
    <label v-show="!username" class="mdl-textfield__label" for="login_name_input">Aktenzeichen</label>
    <span class="mdl-textfield__error">Eingabe erforderlich</span>
  </div>

  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label jp-textfield jp-login-form__textfield">
    <input id="login_password_input" class="mdl-textfield__input" :type="hidePW ? 'password' : 'text'" name="password" 
      v-model="password" autocomplete="current-password" required>
    <label v-show="!password" class="mdl-textfield__label" for="login_password_input">Passwort</label>
    <span class="mdl-textfield__error">Eingabe erforderlich</span>
    <i class="material-icons mdl-textfield__label__icon" 
      @mouseleave="hidePW = true"
      @mouseup="hidePW = true"
      @mousedown="hidePW = false"
    >{{hidePW ? 'visibility_off' : 'visibility'}}</i>
  </div>

  <div class="jp-login-form__textfield jp-login-button">
    <button id="submit_login_button" :disabled="isLoading || username === '' || password === ''" 
      class="mdl-button mdl-js-button mdl-button--raised jp-login-form__button" type="submit">     
      <div v-if="!isLoading" class="jp-login-form__button-text">Anmelden</div>
      <rotationg-refresh v-else/>
    </button>

    <span class="msg-error" v-if="errorMessage">
      {{ errorMessage }}
    </span>
  </div>
</form>

</template>

<style lang="stylus" scoped>
.msg-error
  color darkred
  padding-left 2em

.jp-login-form .mdl-textfield
  width 345px

.jp-login-button
  padding-top 20px
  padding-bottom 20px

.mdl-textfield__label__icon
  position absolute
  right 0
  top 20px
  cursor pointer

</style>
