// src/components/auth/refresh-info/refresh-info.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService, AuthStore } from '@jp-suite/core';
import { DebugContext } from '@angular/core/src/view';
import { debug } from 'util';

import { Subscription } from 'rxjs/internal/Subscription';
import { timer } from 'rxjs';
import { duration, now } from 'moment';
import { AuthInfo } from 'libs/core/src/lib/model/auth-info';

@Component({
  selector: 'jp-refresh-info',
  templateUrl: './refresh-info.component.html',
  styleUrls: ['./refresh-info.component.css']
})
export class RefreshInfoComponent implements OnInit {

  private _updateTimerSub: Subscription;
  public SnackbarVisible:boolean;
  public ShowSnackbar:boolean;
  private SECONDS = 60;

  constructor(private authService: AuthService, public auth: AuthStore) {
  }

  ngOnInit() {
    this.resetTimer();
  }

  resetTimer() {
    this._updateTimerSub = timer(0, 1000).subscribe(t => {
      const authInfo:AuthInfo = this.auth.getAuthInfo();
      if(!authInfo) {
        this.ShowSnackbar=false;
        this.SnackbarVisible=false;
      }
      if(authInfo) {
        const sec=duration(authInfo.expiresAt.diff(now())).asSeconds();
        if (sec<this.SECONDS) { this.ShowSnackbar=true; }
        else { this.ShowSnackbar=false; }
        if (sec<=(this.SECONDS+1)) { this.SnackbarVisible=true; }
        else { this.SnackbarVisible=false; }
      }
    });
  }

  refresh() {
    this.authService.refresh().subscribe(
      () => { }
    );
    this.ShowSnackbar=false;
  }

}

<div *ngIf="SnackbarVisible" class="mdl-snackbar" [ngClass]="{'mdl-snackbar--active': ShowSnackbar }">
  <div class="mdl-snackbar__text">
    Achtung, Ihre Sitzung läuft bald ab!
  </div>
  <div class="mdl-snackbar__button">
    <button  class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" (click)="refresh()">
        <i class="material-icons">refresh</i>
    </button>
  </div>
</div>

// jupo-webui/src/components/auth/RefreshInfo.vue
<script lang="ts" setup>
  function refresh(){}
  function resetTimer(){}

  var _updateTimerSub = null
  var SnackbarVisible = false
  var ShowSnackbar = false
  var SECONDS = 60
</script>

<template>
  <div v-if="SnackbarVisible" class="mdl-snackbar" :class="{'mdl-snackbar--active': ShowSnackbar }">
    <div class="mdl-snackbar__text">
      Achtung, Ihre Sitzung läuft bald ab!
    </div>
    <div class="mdl-snackbar__button">
      <button id="refresh_token_alert_button" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" @click="refresh()">
          <i class="material-icons">refresh</i>
      </button>
    </div>
  </div>
</template>

<style lang="stylus" scoped>
.mdl-snackbar 
  background-color: rgb(135,29,51);

.mdl-snackbar__text
  font-size: 26px;
  line-height: normal;
  align-self:center;

.material-icons
  font-size: 40px;
  height: unset !important;
  width: unset !important;

.mdl-button
  background: whitesmoke;
  height: 50px;

.mdl-snackbar__button
  align-self:center;
  padding:14px 24px 14px 12px;
</style>
